# Generated by Django 6.0 on 2025-12-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
