# Generated by Django 6.0 on 2025-12-27 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name',
        ),
    ]
