# Generated by Django 6.0 on 2026-03-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_usermodel_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_staff',
        ),
    ]
