# Generated by Django 6.0 on 2026-05-08 12:59

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_usermodel_is_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
    ]
