# Generated by Django 6.0 on 2026-05-10 18:39

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_usermodel_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
